
module axi_ssd1306_core #(
    parameter integer AXI_ADDR_WIDTH   = 32       ,
    parameter integer AXI_DATA_WIDTH   = 32       ,
    parameter         CLK_PERIOD       = 100000000,
    parameter         CLK_I2C_PERIOD   = 25000000 ,
    parameter         AXIS_DATA_WIDTH  = 32       ,
    parameter         AXIS_DEPTH       = 32       ,
    parameter         SIZE_WIDTH       = 8        ,
    parameter integer S_AXI_ID_WIDTH   = 0        ,
    parameter integer S_AXI_DATA_WIDTH = 32       ,
    parameter integer S_AXI_ADDR_WIDTH = 8
) (
    input  logic                            i_clk                ,
    input  logic                            i_resetn             ,
    //
    input  logic                            i_cfg_update_screen  ,
    input  logic [      AXI_ADDR_WIDTH-1:0] i_cfg_axi_baseaddress,
    input  logic [                     7:0] i_cfg_iic_address    ,
    input  logic                            i_cfg_initialize     ,
    input  logic                            i_cfg_selector       ,
    // interface to memory
    output logic [      AXI_ADDR_WIDTH-1:0] o_m_axi_araddr       ,
    output logic [                     7:0] o_m_axi_arlen        ,
    output logic [                     2:0] o_m_axi_arsize       ,
    output logic [                     1:0] o_m_axi_arburst      ,
    output logic                            o_m_axi_arvalid      ,
    input  logic                            i_m_axi_arready      ,
    //
    input  logic [      AXI_DATA_WIDTH-1:0] i_m_axi_rdata        ,
    input  logic [                     1:0] i_m_axi_rresp        ,
    input  logic                            i_m_axi_rlast        ,
    input  logic                            i_m_axi_rvalid       ,
    output logic                            o_m_axi_rready       ,
    //
    input  logic                            S_AXI_ACLK           ,
    input  logic                            S_AXI_ARESETN        ,
    input  logic [      S_AXI_ID_WIDTH-1:0] S_AXI_AWID           ,
    input  logic [    S_AXI_ADDR_WIDTH-1:0] S_AXI_AWADDR         ,
    input  logic [                     7:0] S_AXI_AWLEN          ,
    input  logic [                     2:0] S_AXI_AWSIZE         ,
    input  logic [                     1:0] S_AXI_AWBURST        ,
    input  logic                            S_AXI_AWLOCK         ,
    input  logic [                     3:0] S_AXI_AWCACHE        ,
    input  logic [                     2:0] S_AXI_AWPROT         ,
    input  logic [                     3:0] S_AXI_AWQOS          ,
    input  logic [                     3:0] S_AXI_AWREGION       ,
    input  logic                            S_AXI_AWVALID        ,
    output logic                            S_AXI_AWREADY        ,
    input  logic [    S_AXI_DATA_WIDTH-1:0] S_AXI_WDATA          ,
    input  logic [(S_AXI_DATA_WIDTH/8)-1:0] S_AXI_WSTRB          ,
    input  logic                            S_AXI_WLAST          ,
    input  logic                            S_AXI_WVALID         ,
    output logic                            S_AXI_WREADY         ,
    output logic [      S_AXI_ID_WIDTH-1:0] S_AXI_BID            ,
    output logic [                     1:0] S_AXI_BRESP          ,
    output logic                            S_AXI_BVALID         ,
    input  logic                            S_AXI_BREADY         ,
    input  logic [      S_AXI_ID_WIDTH-1:0] S_AXI_ARID           ,
    input  logic [    S_AXI_ADDR_WIDTH-1:0] S_AXI_ARADDR         ,
    input  logic [                     7:0] S_AXI_ARLEN          ,
    input  logic [                     2:0] S_AXI_ARSIZE         ,
    input  logic [                     1:0] S_AXI_ARBURST        ,
    input  logic                            S_AXI_ARLOCK         ,
    input  logic [                     3:0] S_AXI_ARCACHE        ,
    input  logic [                     2:0] S_AXI_ARPROT         ,
    input  logic [                     3:0] S_AXI_ARQOS          ,
    input  logic [                     3:0] S_AXI_ARREGION       ,
    input  logic                            S_AXI_ARVALID        ,
    output logic                            S_AXI_ARREADY        ,
    output logic [      S_AXI_ID_WIDTH-1:0] S_AXI_RID            ,
    output logic [    S_AXI_DATA_WIDTH-1:0] S_AXI_RDATA          ,
    output logic [                     1:0] S_AXI_RRESP          ,
    output logic                            S_AXI_RLAST          ,
    output logic                            S_AXI_RVALID         ,
    input  logic                            S_AXI_RREADY         ,
    //
    input  logic                            i_scl_i              ,
    input  logic                            i_sda_i              ,
    output logic                            o_scl_t              ,
    output logic                            o_sda_t
);