
module axi_ssd1306_core_wrapper #(
    parameter integer AXI_ADDR_WIDTH   = 32       ,
    parameter integer AXI_DATA_WIDTH   = 32       ,
    parameter         CLK_PERIOD       = 100000000,
    parameter         CLK_I2C_PERIOD   = 25000000 ,
    parameter         AXIS_DATA_WIDTH  = 32       ,
    parameter         AXIS_DEPTH       = 32       ,
    parameter         SIZE_WIDTH       = 8        ,
    parameter integer S_AXI_ID_WIDTH   = 0        ,
    parameter integer S_AXI_DATA_WIDTH = 32       ,
    parameter integer S_AXI_ADDR_WIDTH = 8
) (
    input  wire                            i_clk                ,
    input  wire                            i_resetn             ,
    //
    input  wire                            i_cfg_update_screen  ,
    input  wire [      AXI_ADDR_WIDTH-1:0] i_cfg_axi_baseaddress,
    input  wire [                     7:0] i_cfg_iic_address    ,
    input  wire                            i_cfg_initialize     ,
    input  wire                            i_cfg_selector       ,
    // intewire to memory
    output wire [      AXI_ADDR_WIDTH-1:0] M_AXI_ARADDR       ,
    output wire [                     7:0] M_AXI_ARLEN        ,
    output wire [                     2:0] M_AXI_ARSIZE       ,
    output wire [                     1:0] M_AXI_ARBURST      ,
    output wire                            M_AXI_ARVALID      ,
    input  wire                            M_AXI_ARREADY      ,
    //
    input  wire [      AXI_DATA_WIDTH-1:0] M_AXI_RDATA        ,
    input  wire [                     1:0] M_AXI_RRESP        ,
    input  wire                            M_AXI_RLAST        ,
    input  wire                            M_AXI_RVALID       ,
    output wire                            M_AXI_RREADY       ,
    //
    input  wire                            S_AXI_ACLK           ,
    input  wire                            S_AXI_ARESETN        ,
    input  wire [      S_AXI_ID_WIDTH-1:0] S_AXI_AWID           ,
    input  wire [    S_AXI_ADDR_WIDTH-1:0] S_AXI_AWADDR         ,
    input  wire [                     7:0] S_AXI_AWLEN          ,
    input  wire [                     2:0] S_AXI_AWSIZE         ,
    input  wire [                     1:0] S_AXI_AWBURST        ,
    input  wire                            S_AXI_AWLOCK         ,
    input  wire [                     3:0] S_AXI_AWCACHE        ,
    input  wire [                     2:0] S_AXI_AWPROT         ,
    input  wire [                     3:0] S_AXI_AWQOS          ,
    input  wire [                     3:0] S_AXI_AWREGION       ,
    input  wire                            S_AXI_AWVALID        ,
    output wire                            S_AXI_AWREADY        ,
    input  wire [    S_AXI_DATA_WIDTH-1:0] S_AXI_WDATA          ,
    input  wire [(S_AXI_DATA_WIDTH/8)-1:0] S_AXI_WSTRB          ,
    input  wire                            S_AXI_WLAST          ,
    input  wire                            S_AXI_WVALID         ,
    output wire                            S_AXI_WREADY         ,
    output wire [      S_AXI_ID_WIDTH-1:0] S_AXI_BID            ,
    output wire [                     1:0] S_AXI_BRESP          ,
    output wire                            S_AXI_BVALID         ,
    input  wire                            S_AXI_BREADY         ,
    input  wire [      S_AXI_ID_WIDTH-1:0] S_AXI_ARID           ,
    input  wire [    S_AXI_ADDR_WIDTH-1:0] S_AXI_ARADDR         ,
    input  wire [                     7:0] S_AXI_ARLEN          ,
    input  wire [                     2:0] S_AXI_ARSIZE         ,
    input  wire [                     1:0] S_AXI_ARBURST        ,
    input  wire                            S_AXI_ARLOCK         ,
    input  wire [                     3:0] S_AXI_ARCACHE        ,
    input  wire [                     2:0] S_AXI_ARPROT         ,
    input  wire [                     3:0] S_AXI_ARQOS          ,
    input  wire [                     3:0] S_AXI_ARREGION       ,
    input  wire                            S_AXI_ARVALID        ,
    output wire                            S_AXI_ARREADY        ,
    output wire [      S_AXI_ID_WIDTH-1:0] S_AXI_RID            ,
    output wire [    S_AXI_DATA_WIDTH-1:0] S_AXI_RDATA          ,
    output wire [                     1:0] S_AXI_RRESP          ,
    output wire                            S_AXI_RLAST          ,
    output wire                            S_AXI_RVALID         ,
    input  wire                            S_AXI_RREADY         ,
    //
    input  wire                            i_scl_i              ,
    input  wire                            i_sda_i              ,
    output wire                            o_scl_t              ,
    output wire                            o_sda_t
);



    axi_ssd1306_core #(
        .AXI_ADDR_WIDTH  (AXI_ADDR_WIDTH  ),
        .AXI_DATA_WIDTH  (AXI_DATA_WIDTH  ),
        .CLK_PERIOD      (CLK_PERIOD      ),
        .CLK_I2C_PERIOD  (CLK_I2C_PERIOD  ),
        .AXIS_DATA_WIDTH (AXIS_DATA_WIDTH ),
        .AXIS_DEPTH      (AXIS_DEPTH      ),
        .SIZE_WIDTH      (SIZE_WIDTH      ),
        .S_AXI_ID_WIDTH  (S_AXI_ID_WIDTH  ),
        .S_AXI_DATA_WIDTH(S_AXI_DATA_WIDTH),
        .S_AXI_ADDR_WIDTH(S_AXI_ADDR_WIDTH)
    ) axi_ssd1306_core_inst (
        .i_clk                (i_clk                ),
        .i_resetn             (i_resetn             ),
        //
        .i_cfg_update_screen  (i_cfg_update_screen  ),
        .i_cfg_axi_baseaddress(i_cfg_axi_baseaddress),
        .i_cfg_iic_address    (i_cfg_iic_address    ),
        .i_cfg_initialize     (i_cfg_initialize     ),
        .i_cfg_selector       (i_cfg_selector       ),
        // interface to memory
        .o_m_axi_araddr       (M_AXI_ARADDR       ),
        .o_m_axi_arlen        (M_AXI_ARLEN        ),
        .o_m_axi_arsize       (M_AXI_ARSIZE       ),
        .o_m_axi_arburst      (M_AXI_ARBURST      ),
        .o_m_axi_arvalid      (M_AXI_ARVALID      ),
        .i_m_axi_arready      (M_AXI_ARREADY      ),
        //
        .i_m_axi_rdata        (M_AXI_RDATA        ),
        .i_m_axi_rresp        (M_AXI_RRESP        ),
        .i_m_axi_rlast        (M_AXI_RLAST        ),
        .i_m_axi_rvalid       (M_AXI_RVALID       ),
        .o_m_axi_rready       (M_AXI_RREADY       ),
        //
        .S_AXI_ACLK           (S_AXI_ACLK           ),
        .S_AXI_ARESETN        (S_AXI_ARESETN        ),
        .S_AXI_AWID           (S_AXI_AWID           ),
        .S_AXI_AWADDR         (S_AXI_AWADDR         ),
        .S_AXI_AWLEN          (S_AXI_AWLEN          ),
        .S_AXI_AWSIZE         (S_AXI_AWSIZE         ),
        .S_AXI_AWBURST        (S_AXI_AWBURST        ),
        .S_AXI_AWLOCK         (S_AXI_AWLOCK         ),
        .S_AXI_AWCACHE        (S_AXI_AWCACHE        ),
        .S_AXI_AWPROT         (S_AXI_AWPROT         ),
        .S_AXI_AWQOS          (S_AXI_AWQOS          ),
        .S_AXI_AWREGION       (S_AXI_AWREGION       ),
        .S_AXI_AWVALID        (S_AXI_AWVALID        ),
        .S_AXI_AWREADY        (S_AXI_AWREADY        ),
        .S_AXI_WDATA          (S_AXI_WDATA          ),
        .S_AXI_WSTRB          (S_AXI_WSTRB          ),
        .S_AXI_WLAST          (S_AXI_WLAST          ),
        .S_AXI_WVALID         (S_AXI_WVALID         ),
        .S_AXI_WREADY         (S_AXI_WREADY         ),
        .S_AXI_BID            (S_AXI_BID            ),
        .S_AXI_BRESP          (S_AXI_BRESP          ),
        .S_AXI_BVALID         (S_AXI_BVALID         ),
        .S_AXI_BREADY         (S_AXI_BREADY         ),
        .S_AXI_ARID           (S_AXI_ARID           ),
        .S_AXI_ARADDR         (S_AXI_ARADDR         ),
        .S_AXI_ARLEN          (S_AXI_ARLEN          ),
        .S_AXI_ARSIZE         (S_AXI_ARSIZE         ),
        .S_AXI_ARBURST        (S_AXI_ARBURST        ),
        .S_AXI_ARLOCK         (S_AXI_ARLOCK         ),
        .S_AXI_ARCACHE        (S_AXI_ARCACHE        ),
        .S_AXI_ARPROT         (S_AXI_ARPROT         ),
        .S_AXI_ARQOS          (S_AXI_ARQOS          ),
        .S_AXI_ARREGION       (S_AXI_ARREGION       ),
        .S_AXI_ARVALID        (S_AXI_ARVALID        ),
        .S_AXI_ARREADY        (S_AXI_ARREADY        ),
        .S_AXI_RID            (S_AXI_RID            ),
        .S_AXI_RDATA          (S_AXI_RDATA          ),
        .S_AXI_RRESP          (S_AXI_RRESP          ),
        .S_AXI_RLAST          (S_AXI_RLAST          ),
        .S_AXI_RVALID         (S_AXI_RVALID         ),
        .S_AXI_RREADY         (S_AXI_RREADY         ),
        //
        .i_scl_i              (i_scl_i              ),
        .i_sda_i              (i_sda_i              ),
        .o_scl_t              (o_scl_t              ),
        .o_sda_t              (o_sda_t              )
    );


endmodule 