
module axi_ssd1306_core_wrapper #(
    parameter integer AXI_ADDR_WIDTH   = 32       ,
    parameter integer AXI_DATA_WIDTH   = 32       ,
    parameter         CLK_PERIOD       = 100000000,
    parameter         CLK_I2C_PERIOD   = 25000000 ,
    parameter         AXIS_DATA_WIDTH  = 32       ,
    parameter         AXIS_DEPTH       = 32       ,
    parameter         SIZE_WIDTH       = 8        ,
    parameter integer S_AXI_ID_WIDTH   = 0        ,
    parameter integer S_AXI_DATA_WIDTH = 32       ,
    parameter integer S_AXI_ADDR_WIDTH = 8
) (
    input  wire                            i_clk                ,
    input  wire                            i_resetn             ,
    //
    input  wire                            i_cfg_update_screen  ,
    input  wire [      AXI_ADDR_WIDTH-1:0] i_cfg_axi_baseaddress,
    input  wire [                     7:0] i_cfg_iic_address    ,
    input  wire                            i_cfg_initialize     ,
    input  wire                            i_cfg_selector       ,
    input  wire [                    31:0] i_cfg_duration       ,
    input  wire [                     2:0] i_cfg_segment_limit  , // 4 or 8
    // intewire to memory
    output wire [      AXI_ADDR_WIDTH-1:0] M_AXI_UPD_ARADDR     ,
    output wire [                     7:0] M_AXI_UPD_ARLEN      ,
    output wire [                     2:0] M_AXI_UPD_ARSIZE     ,
    output wire [                     1:0] M_AXI_UPD_ARBURST    ,
    output wire                            M_AXI_UPD_ARVALID    ,
    input  wire                            M_AXI_UPD_ARREADY    ,
    //
    input  wire [      AXI_DATA_WIDTH-1:0] M_AXI_UPD_RDATA      ,
    input  wire [                     1:0] M_AXI_UPD_RRESP      ,
    input  wire                            M_AXI_UPD_RLAST      ,
    input  wire                            M_AXI_UPD_RVALID     ,
    output wire                            M_AXI_UPD_RREADY     ,
    //
    input  wire                            S_AXI_UCODE_ACLK     ,
    input  wire                            S_AXI_UCODE_ARESETN  ,
    input  wire [      S_AXI_ID_WIDTH-1:0] S_AXI_UCODE_AWID     ,
    input  wire [    S_AXI_ADDR_WIDTH-1:0] S_AXI_UCODE_AWADDR   ,
    input  wire [                     7:0] S_AXI_UCODE_AWLEN    ,
    input  wire [                     2:0] S_AXI_UCODE_AWSIZE   ,
    input  wire [                     1:0] S_AXI_UCODE_AWBURST  ,
    input  wire                            S_AXI_UCODE_AWLOCK   ,
    input  wire [                     3:0] S_AXI_UCODE_AWCACHE  ,
    input  wire [                     2:0] S_AXI_UCODE_AWPROT   ,
    input  wire [                     3:0] S_AXI_UCODE_AWQOS    ,
    input  wire [                     3:0] S_AXI_UCODE_AWREGION ,
    input  wire                            S_AXI_UCODE_AWVALID  ,
    output wire                            S_AXI_UCODE_AWREADY  ,
    input  wire [    S_AXI_DATA_WIDTH-1:0] S_AXI_UCODE_WDATA    ,
    input  wire [(S_AXI_DATA_WIDTH/8)-1:0] S_AXI_UCODE_WSTRB    ,
    input  wire                            S_AXI_UCODE_WLAST    ,
    input  wire                            S_AXI_UCODE_WVALID   ,
    output wire                            S_AXI_UCODE_WREADY   ,
    output wire [      S_AXI_ID_WIDTH-1:0] S_AXI_UCODE_BID      ,
    output wire [                     1:0] S_AXI_UCODE_BRESP    ,
    output wire                            S_AXI_UCODE_BVALID   ,
    input  wire                            S_AXI_UCODE_BREADY   ,
    input  wire [      S_AXI_ID_WIDTH-1:0] S_AXI_UCODE_ARID     ,
    input  wire [    S_AXI_ADDR_WIDTH-1:0] S_AXI_UCODE_ARADDR   ,
    input  wire [                     7:0] S_AXI_UCODE_ARLEN    ,
    input  wire [                     2:0] S_AXI_UCODE_ARSIZE   ,
    input  wire [                     1:0] S_AXI_UCODE_ARBURST  ,
    input  wire                            S_AXI_UCODE_ARLOCK   ,
    input  wire [                     3:0] S_AXI_UCODE_ARCACHE  ,
    input  wire [                     2:0] S_AXI_UCODE_ARPROT   ,
    input  wire [                     3:0] S_AXI_UCODE_ARQOS    ,
    input  wire [                     3:0] S_AXI_UCODE_ARREGION ,
    input  wire                            S_AXI_UCODE_ARVALID  ,
    output wire                            S_AXI_UCODE_ARREADY  ,
    output wire [      S_AXI_ID_WIDTH-1:0] S_AXI_UCODE_RID      ,
    output wire [    S_AXI_DATA_WIDTH-1:0] S_AXI_UCODE_RDATA    ,
    output wire [                     1:0] S_AXI_UCODE_RRESP    ,
    output wire                            S_AXI_UCODE_RLAST    ,
    output wire                            S_AXI_UCODE_RVALID   ,
    input  wire                            S_AXI_UCODE_RREADY   ,
    //
    input  wire                            i_scl_i              ,
    input  wire                            i_sda_i              ,
    output wire                            o_scl_t              ,
    output wire                            o_sda_t
);



    axi_ssd1306_core #(
        .AXI_ADDR_WIDTH        (AXI_ADDR_WIDTH  ),
        .AXI_DATA_WIDTH        (AXI_DATA_WIDTH  ),
        .CLK_PERIOD            (CLK_PERIOD      ),
        .CLK_I2C_PERIOD        (CLK_I2C_PERIOD  ),
        .AXIS_DATA_WIDTH       (AXIS_DATA_WIDTH ),
        .AXIS_DEPTH            (AXIS_DEPTH      ),
        .SIZE_WIDTH            (SIZE_WIDTH      ),
        .S_AXI_UCODE_ID_WIDTH  (S_AXI_ID_WIDTH  ),
        .S_AXI_UCODE_DATA_WIDTH(S_AXI_DATA_WIDTH),
        .S_AXI_UCODE_ADDR_WIDTH(S_AXI_ADDR_WIDTH)
    ) axi_ssd1306_core_inst (
        .i_clk                (i_clk                ),
        .i_resetn             (i_resetn             ),
        //
        .i_cfg_update_screen  (i_cfg_update_screen  ),
        .i_cfg_axi_baseaddress(i_cfg_axi_baseaddress),
        .i_cfg_iic_address    (i_cfg_iic_address    ),
        .i_cfg_initialize     (i_cfg_initialize     ),
        .i_cfg_selector       (i_cfg_selector       ),
        
        .i_cfg_duration       (i_cfg_duration       ),
        .i_cfg_segment_limit  (i_cfg_segment_limit  ),   // 4 or 8
        // interface to memory
        .M_AXI_UPD_ARADDR     (M_AXI_UPD_ARADDR     ),
        .M_AXI_UPD_ARLEN      (M_AXI_UPD_ARLEN      ),
        .M_AXI_UPD_ARSIZE     (M_AXI_UPD_ARSIZE     ),
        .M_AXI_UPD_ARBURST    (M_AXI_UPD_ARBURST    ),
        .M_AXI_UPD_ARVALID    (M_AXI_UPD_ARVALID    ),
        .M_AXI_UPD_ARREADY    (M_AXI_UPD_ARREADY    ),
        //
        .M_AXI_UPD_RDATA      (M_AXI_UPD_RDATA      ),
        .M_AXI_UPD_RRESP      (M_AXI_UPD_RRESP      ),
        .M_AXI_UPD_RLAST      (M_AXI_UPD_RLAST      ),
        .M_AXI_UPD_RVALID     (M_AXI_UPD_RVALID     ),
        .M_AXI_UPD_RREADY     (M_AXI_UPD_RREADY     ),
        //
        .S_AXI_UCODE_ACLK     (S_AXI_UCODE_ACLK     ),
        .S_AXI_UCODE_ARESETN  (S_AXI_UCODE_ARESETN  ),
        .S_AXI_UCODE_AWID     (S_AXI_UCODE_AWID     ),
        .S_AXI_UCODE_AWADDR   (S_AXI_UCODE_AWADDR   ),
        .S_AXI_UCODE_AWLEN    (S_AXI_UCODE_AWLEN    ),
        .S_AXI_UCODE_AWSIZE   (S_AXI_UCODE_AWSIZE   ),
        .S_AXI_UCODE_AWBURST  (S_AXI_UCODE_AWBURST  ),
        .S_AXI_UCODE_AWLOCK   (S_AXI_UCODE_AWLOCK   ),
        .S_AXI_UCODE_AWCACHE  (S_AXI_UCODE_AWCACHE  ),
        .S_AXI_UCODE_AWPROT   (S_AXI_UCODE_AWPROT   ),
        .S_AXI_UCODE_AWQOS    (S_AXI_UCODE_AWQOS    ),
        .S_AXI_UCODE_AWREGION (S_AXI_UCODE_AWREGION ),
        .S_AXI_UCODE_AWVALID  (S_AXI_UCODE_AWVALID  ),
        .S_AXI_UCODE_AWREADY  (S_AXI_UCODE_AWREADY  ),
        .S_AXI_UCODE_WDATA    (S_AXI_UCODE_WDATA    ),
        .S_AXI_UCODE_WSTRB    (S_AXI_UCODE_WSTRB    ),
        .S_AXI_UCODE_WLAST    (S_AXI_UCODE_WLAST    ),
        .S_AXI_UCODE_WVALID   (S_AXI_UCODE_WVALID   ),
        .S_AXI_UCODE_WREADY   (S_AXI_UCODE_WREADY   ),
        .S_AXI_UCODE_BID      (S_AXI_UCODE_BID      ),
        .S_AXI_UCODE_BRESP    (S_AXI_UCODE_BRESP    ),
        .S_AXI_UCODE_BVALID   (S_AXI_UCODE_BVALID   ),
        .S_AXI_UCODE_BREADY   (S_AXI_UCODE_BREADY   ),
        .S_AXI_UCODE_ARID     (S_AXI_UCODE_ARID     ),
        .S_AXI_UCODE_ARADDR   (S_AXI_UCODE_ARADDR   ),
        .S_AXI_UCODE_ARLEN    (S_AXI_UCODE_ARLEN    ),
        .S_AXI_UCODE_ARSIZE   (S_AXI_UCODE_ARSIZE   ),
        .S_AXI_UCODE_ARBURST  (S_AXI_UCODE_ARBURST  ),
        .S_AXI_UCODE_ARLOCK   (S_AXI_UCODE_ARLOCK   ),
        .S_AXI_UCODE_ARCACHE  (S_AXI_UCODE_ARCACHE  ),
        .S_AXI_UCODE_ARPROT   (S_AXI_UCODE_ARPROT   ),
        .S_AXI_UCODE_ARQOS    (S_AXI_UCODE_ARQOS    ),
        .S_AXI_UCODE_ARREGION (S_AXI_UCODE_ARREGION ),
        .S_AXI_UCODE_ARVALID  (S_AXI_UCODE_ARVALID  ),
        .S_AXI_UCODE_ARREADY  (S_AXI_UCODE_ARREADY  ),
        .S_AXI_UCODE_RID      (S_AXI_UCODE_RID      ),
        .S_AXI_UCODE_RDATA    (S_AXI_UCODE_RDATA    ),
        .S_AXI_UCODE_RRESP    (S_AXI_UCODE_RRESP    ),
        .S_AXI_UCODE_RLAST    (S_AXI_UCODE_RLAST    ),
        .S_AXI_UCODE_RVALID   (S_AXI_UCODE_RVALID   ),
        .S_AXI_UCODE_RREADY   (S_AXI_UCODE_RREADY   ),
        //
        .i_scl_i              (i_scl_i              ),
        .i_sda_i              (i_sda_i              ),
        .o_scl_t              (o_scl_t              ),
        .o_sda_t              (o_sda_t              )
    );


endmodule 